workflows:

  ios-release:

    name: iOS Release Build

    max_build_duration: 120

    environment:

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.residenceconnect.myapp

      vars:
        XCODE_WORKSPACE: "MyGate.xcworkspace"
        XCODE_SCHEME: "MyGate"
        RCT_NEW_ARCH_ENABLED: "0"
        NODE_OPTIONS: "--max_old_space_size=8192"

      node: latest
      xcode: 16.4
      cocoapods: default

    integrations:
      app_store_connect: Codemagic Key

    scripts:

      - name: Install dependencies
        script: |
          npm install

      - name: Clean iOS & Install Pods
        script: |
          cd ios

          rm -rf Pods
          rm -rf build
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -f Podfile.lock

          pod deintegrate

          RCT_NEW_ARCH_ENABLED=0 pod install --repo-update

      - name: Verify workspace
        script: |
          ls ios

      - name: Set up code signing
        script: |
          cd ios
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/Archives/**/*.xcarchive

    publishing:

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

      email:
        recipients:
          - your-email@gmail.com