import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../../theme/colors';

export const createStyles = (
  colors: ThemeColors,
  options: { isCompactWidth: boolean; isCompactHeight: boolean; bottomInset: number },
) =>
  StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: options.isCompactWidth ? 16 : 20,
    paddingBottom: Math.max(options.bottomInset, 12) + (options.isCompactHeight ? 10 : 16),
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: Math.max(options.bottomInset, 12) + (options.isCompactHeight ? 28 : 18),
  },
  card: {
    flexGrow: 1,
    minHeight: options.isCompactHeight ? 0 : 520,
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: options.isCompactWidth ? 12 : 14,
    marginBottom: 12,
    shadowColor: colors.overlay,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  label: {
    fontSize: options.isCompactWidth ? 10.5 : 11,
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: options.isCompactHeight ? 8 : 10,
  },
  valueBox: {
    minHeight: options.isCompactHeight ? 40 : 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    paddingHorizontal: 10,
    backgroundColor: colors.surfaceMuted,
  },
  valueText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  input: {
    minHeight: options.isCompactHeight ? 40 : 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 10,
    color: colors.textPrimary,
    justifyContent: 'center',
  },
  dateTimeText: {
    color: colors.textPrimary,
    fontSize: 13,
  },
  dateTimePlaceholderText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  multiline: {
    minHeight: options.isCompactHeight ? 72 : 78,
    textAlignVertical: 'top',
    paddingTop: 10,
  },
  modeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 8,
    marginBottom: 4,
    gap: 8,
  },
  modeButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modeButtonActive: {
    backgroundColor: colors.backgroundAlt,
    borderColor: colors.primary,
  },
  modeText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  modeTextActive: {
    color: colors.primary,
  },
  listenButton: {
    marginLeft: 'auto',
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  listenButtonText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  urgencyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  urgencyButton: {
    flex: 1,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  urgencyButtonActive: {
    backgroundColor: colors.backgroundAlt,
    borderColor: colors.primary,
  },
  urgencyText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  urgencyTextActive: {
    color: colors.primary,
  },
  actionRow: {
    flexDirection: options.isCompactWidth ? 'column' : 'row',
    marginTop: 2,
    marginBottom: Math.max(options.bottomInset, 8) + (options.isCompactHeight ? 8 : 4),
    justifyContent: 'space-between',
    gap: options.isCompactWidth || options.isCompactHeight ? 10 : 0,
  },
  saveButton: {
    flex: 1,
    minHeight: options.isCompactHeight ? 46 : 44,
    backgroundColor: colors.primary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: options.isCompactWidth || options.isCompactHeight ? 0 : 10,
  },
  cancelButton: {
    flex: 1,
    minHeight: options.isCompactHeight ? 46 : 44,
    backgroundColor: colors.danger,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: {
    color: colors.onPrimary,
    fontWeight: '700',
    fontSize: 14,
  },
  actionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  successOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  successIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    marginBottom: 16,
  },
  successTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  successText: {
    marginTop: 8,
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  successActionPrimary: {
    width: '100%',
    minHeight: 48,
    marginTop: 18,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successActionSecondary: {
    width: '100%',
    minHeight: 48,
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successActionPrimaryText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  successActionSecondaryText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  });
