import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../../theme/colors';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 20,
    },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    contentContainer: {
      paddingBottom: 32,
    },
    heroCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 20,
      marginBottom: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.overlay,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 5,
    },
    heroCircle1: {
      position: 'absolute',
      top: -48,
      right: -36,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: 'rgba(232,119,34,0.16)',
    },
    heroCircle2: {
      position: 'absolute',
      bottom: -28,
      left: -28,
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: 'rgba(245,158,11,0.12)',
    },
    heroEyebrow: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1,
      opacity: 0.92,
    },
    heroTitle: {
      marginTop: 10,
      color: colors.textPrimary,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '800',
    },
    heroSub: {
      marginTop: 8,
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    metaRow: {
      marginTop: 18,
      flexDirection: 'row',
      gap: 10,
    },
    metaPill: {
      flex: 1,
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    metaPillSingle: {
      width: 132,
      backgroundColor: colors.surfaceMuted,
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    metaPillLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    metaPillValue: {
      marginTop: 4,
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    historyAction: {
      minHeight: 38,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    historyActionText: {
      color: colors.onPrimary,
      fontSize: 12,
      fontWeight: '800',
    },
    errorText: {
      color: colors.danger,
      fontSize: 13,
      marginBottom: 12,
      textAlign: 'center',
    },
    emptyCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    emptyText: {
      marginTop: 8,
      fontSize: 14,
      lineHeight: 20,
      color: colors.textMuted,
      textAlign: 'center',
    },
    emptyHint: {
      marginTop: 14,
      fontSize: 12,
      lineHeight: 18,
      color: colors.textMuted,
      textAlign: 'center',
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.overlay,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 2,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatar: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: colors.backgroundAlt,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      overflow: 'hidden',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
    },
    avatarText: {
      color: colors.primary,
      fontSize: 20,
      fontWeight: '800',
    },
    headerContent: {
      flex: 1,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    name: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 17,
      fontWeight: '800',
    },
    selectedBadge: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 999,
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    selectedBadgeText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '700',
    },
    role: {
      marginTop: 4,
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    phoneText: {
      marginTop: 4,
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '600',
    },
    quickGrid: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 10,
    },
    quickItem: {
      flex: 1,
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    quickLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    quickValue: {
      marginTop: 4,
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    detailBlock: {
      marginTop: 10,
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    detailLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
    },
    detailValue: {
      marginTop: 4,
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    skillsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 10,
    },
    skillPill: {
      backgroundColor: colors.backgroundAlt,
      borderRadius: 999,
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    skillText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 12,
      gap: 12,
    },
    callButton: {
      width: 48,
      height: 48,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
    },
    selectButton: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    selectButtonDisabled: {
      opacity: 0.65,
    },
    selectButtonText: {
      color: colors.onPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    selectButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
  });
