# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# AndroidX
android.useAndroidX=true

# Explicitly enable BuildConfig generation
android.defaults.buildfeatures.buildconfig=true

# React Native architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a

# React Native New Architecture
# Keep disabled if your project/libraries are not ready for it.
# newArchEnabled=false

# Hermes JS engine
hermesEnabled=true

# Edge-to-edge display support
edgeToEdgeEnabled=false