# Resolve react_native_pods.rb with node
require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
    __dir__
  ]
).strip

platform :ios, '15.1'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

prepare_react_native_project!

target 'MyGate' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.generated_projects.each do |project|

      project.targets.each do |target|

        target.build_configurations.each do |config|

          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

          # ONLY THIS
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

          # DO NOT SET:
          # CODE_SIGN_IDENTITY
          # EXPANDED_CODE_SIGN_IDENTITY
          # CODE_SIGNING_REQUIRED
          # DEVELOPMENT_TEAM

        end
      end
    end
  end
end