# Resolve react_native_pods.rb with node
require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
    __dir__
  ]
).strip

platform :ios, '15.1'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

prepare_react_native_project!

target 'MyGate' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.generated_projects.each do |project|

      project.targets.each do |target|

        target.build_configurations.each do |config|

          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'

          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'

          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=c++17'

          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error'

        end
      end
    end
  end
end