import { Dimensions, StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../../theme/colors';

const { width } = Dimensions.get('window');

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
  // Main Smart Access Screen
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingTop: 20,
  },

  // Simple Door Grid (Main Screen)
  simpleDoorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  simpleDoorTile: {
    width: (width - 72) / 3, // 3 columns on wider screens, will wrap to 2 rows
    minHeight: 110,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
  },
  simpleDoorIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  simpleDoorLabel: {
    textAlign: 'center',
    fontSize: 12,
    color: colors.textPrimary,
    fontWeight: '600',
    lineHeight: 16,
  },
  scrollContent: {
    paddingBottom: 28,
    gap: 14,
  },
  accessHeroCard: {
    overflow: 'hidden',
    backgroundColor: '#102A43',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    minHeight: 156,
    justifyContent: 'flex-end',
  },
  accessHeroGlow: {
    position: 'absolute',
    top: -28,
    right: -8,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  accessHeroEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.72)',
    marginBottom: 8,
  },
  accessHeroTitle: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    maxWidth: 240,
  },
  accessHeroText: {
    marginTop: 10,
    fontSize: 13,
    lineHeight: 19,
    color: 'rgba(255,255,255,0.82)',
    maxWidth: 272,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  sectionHeaderContent: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sectionCaption: {
    marginTop: 4,
    fontSize: 12,
    color: colors.textMuted,
  },
  doorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  doorCard: {
    width: (width - 84) / 2,
    minHeight: 120,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  accessDeviceCard: {
    width: (width - 84) / 2,
    minHeight: 196,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 16,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  accessDeviceCardSelected: {
    borderColor: colors.primary,
    transform: [{ translateY: -2 }],
  },
  accessDeviceAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: colors.primary,
    opacity: 0.9,
  },
  doorIconCircle: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  doorName: {
    textAlign: 'center',
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '700',
  },
  accessDeviceSubtitle: {
    marginTop: 6,
    textAlign: 'center',
    fontSize: 11,
    color: colors.textMuted,
    lineHeight: 16,
    minHeight: 16,
  },
  accessDeviceMeta: {
    marginTop: 6,
    textAlign: 'center',
    fontSize: 10,
    color: colors.textSecondary,
    lineHeight: 14,
    minHeight: 14,
  },
  accessTileFooter: {
    marginTop: 'auto',
    paddingTop: 14,
    width: '100%',
    alignItems: 'center',
  },
  accessTilePill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  accessTilePillText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  accessActionRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  accessActionBtn: {
    flex: 1,
    minHeight: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  accessUnlockBtn: {
    backgroundColor: colors.primary,
  },
  accessLockBtn: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  accessActionBtnBusy: {
    opacity: 0.7,
  },
  accessActionBtnText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  accessLockBtnText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  accessRefreshBtn: {
    minWidth: 76,
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
    flexShrink: 0,
  },
  accessRefreshText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  accessStateWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 8,
  },
  accessStateText: {
    textAlign: 'center',
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
  },
  accessModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  accessModalBackdrop: {
    flex: 1,
  },
  accessModalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 30,
    minHeight: 370,
  },
  accessModalHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.border,
    alignSelf: 'center',
    marginBottom: 18,
  },
  accessModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  accessModalIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 22,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessModalClose: {
    minWidth: 74,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.backgroundAlt,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  accessModalCloseText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  accessModalTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  accessModalSubtitle: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textMuted,
  },
  accessModalInfoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  accessModalInfoChip: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  accessModalInfoChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  accessModalDescription: {
    marginTop: 18,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSecondary,
  },
  accessModalActionStack: {
    marginTop: 24,
    gap: 12,
  },
  accessModalPrimaryBtn: {
    borderRadius: 22,
    backgroundColor: colors.primary,
    paddingHorizontal: 18,
    paddingVertical: 18,
    minHeight: 92,
    justifyContent: 'center',
  },
  accessModalPrimaryTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.onPrimary,
  },
  accessModalPrimaryText: {
    marginTop: 5,
    fontSize: 13,
    lineHeight: 19,
    color: 'rgba(255,255,255,0.82)',
  },
  accessModalSecondaryBtn: {
    borderRadius: 22,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 18,
    minHeight: 92,
    justifyContent: 'center',
  },
  accessModalSecondaryTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  accessModalSecondaryText: {
    marginTop: 5,
    fontSize: 13,
    lineHeight: 19,
    color: colors.textSecondary,
  },

  historyContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  historyTopPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  historyPill: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  historyPillText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  historySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  historySectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  historyViewAll: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
  },
  historyListCompact: {
    gap: 12,
  },
  historyCompactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  historyCompactLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  historyCompactIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.backgroundAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyCompactTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  historyCompactStatus: {
    fontSize: 12,
    fontWeight: '700',
  },
  historyCompactDate: {
    fontSize: 12,
    color: colors.textMuted,
  },
historyButton: {
  marginTop: 24,
  backgroundColor: colors.primary,
  borderRadius: 12,
  paddingVertical: 14,
  paddingHorizontal: 20,
  alignItems: 'center',
  shadowColor: colors.overlay,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 2,
},
historyButtonText: {
  fontSize: 14,
  fontWeight: '600',
  color: colors.onPrimary, 
},
});
