// HomeScreen.styles.ts
import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../../theme/colors';

export const createStyles = (colors: ThemeColors, isDark: boolean) =>
  StyleSheet.create({

    // ── Root ─────────────────────────────────────
    container: {
      flex: 1,
    },
    loaderContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },

    // ── Hero ─────────────────────────────────────
    hero: {
      backgroundColor: '#1C2340',
      paddingTop: 52,
      paddingHorizontal: 20,
      paddingBottom: 24,
      overflow: 'hidden',
      borderRadius: 28,
      marginTop: 12,
    },
    heroCircle1: {
      position: 'absolute',
      top: -60,
      right: -50,
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: 'rgba(108,142,245,0.10)',
    },
    heroCircle2: {
      position: 'absolute',
      bottom: -40,
      left: -40,
      width: 150,
      height: 150,
      borderRadius: 75,
      backgroundColor: 'rgba(232,119,34,0.08)',
    },

    // ── Header row ───────────────────────────────
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
      gap: 12,
      flexWrap: 'wrap',
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      flex: 1,
      minWidth: 0,
    },
    avatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: '#E87722',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.18)',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: 26,
    },
    avatarText: {
      fontSize: 18,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    greeting: {
      fontSize: 13,
      color: '#94A3B8',
      marginBottom: 3,
      fontWeight: '500',
    },
    name: {
      fontSize: 20,
      fontWeight: '800',
      color: '#FFFFFF',
      marginBottom: 6,
      letterSpacing: -0.3,
      flexShrink: 1,
    },
    locationBadge: {
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderRadius: 50,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignSelf: 'flex-start',
      maxWidth: '100%',
    },
    locationText: {
      fontSize: 11,
      color: '#94A3B8',
      fontWeight: '500',
      flexShrink: 1,
    },
    notificationBtn: {
      position: 'relative',
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.16)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.22)',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
      flexShrink: 0,
      marginLeft: 8,
    },
    notificationBadge: {
      position: 'absolute',
      top: -3,
      right: -3,
      backgroundColor: '#EF4444',
      borderRadius: 10,
      minWidth: 18,
      height: 18,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: '#1C2340',
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '700',
    },

    // ── Stat pills ────────────────────────────────
    statsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    statPill: {
      flex: 1,
      minWidth: 92,
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: 'center',
    },
    // icon row inside stat pill
    statBottomRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      gap: 5,
      flexWrap: 'wrap',
    },
    statBottomRowTight: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 6,
      gap: 4,
      flexWrap: 'nowrap',
      width: '100%',
      minWidth: 0,
    },
    statIconWrap: {
      marginBottom: 0,
      flexShrink: 0,
    },
    statNum: {
      fontSize: 20,
      fontWeight: '800',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    statLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: 'rgba(255,255,255,0.70)',
      letterSpacing: 0.5,
      textAlign: 'center',
    },
    statLabelCompact: {
      fontSize: 8,
      fontWeight: '700',
      color: 'rgba(255,255,255,0.70)',
      letterSpacing: 0.35,
      textAlign: 'center',
      flexShrink: 1,
      minWidth: 0,
    },

    // ── Content below hero ────────────────────────
    contentWrapper: {
      paddingTop: 16,
      paddingBottom: 32,
      paddingHorizontal: 16,
    },

    // ── Search ───────────────────────────────────
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 18,
      height: 48,
      paddingHorizontal: 16,
      marginBottom: 14,
      borderWidth: 0.5,
      borderColor: colors.border,
      gap: 10,
      shadowColor: isDark ? '#FFFFFF' : '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.12 : 0.05,
      shadowRadius: isDark ? 10 : 6,
      elevation: isDark ? 4 : 2,
    },
    searchIcon: {
      fontSize: 15,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      height: '100%',
    },
    searchSuggestions: {
      borderRadius: 14,
      marginBottom: 14,
      overflow: 'hidden',
      borderWidth: 0.5,
      borderColor: colors.border,
      shadowColor: isDark ? '#FFFFFF' : '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.12 : 0.06,
      shadowRadius: isDark ? 12 : 8,
      elevation: isDark ? 5 : 3,
    },
    searchSuggestionItem: {
      paddingHorizontal: 16,
      paddingVertical: 13,
      borderBottomWidth: 0.5,
    },
    searchSuggestionText: {
      fontSize: 14,
      fontWeight: '600',
    },
    noResultsWrap: {
      paddingHorizontal: 20,
      paddingVertical: 20,
      alignItems: 'center',
    },
    noResultsText: {
      fontSize: 14,
      textAlign: 'center',
      fontWeight: '500',
    },

    // ── My Neighbors — FULL WIDTH card ───────────
    neighborCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#1C2340',
      borderRadius: 20,
      paddingVertical: 20,
      paddingHorizontal: 20,
      marginBottom: 24,
      shadowColor: isDark ? '#FFFFFF' : '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.18 : 0.15,
      shadowRadius: isDark ? 14 : 12,
      elevation: isDark ? 7 : 5,
    },
    neighborTextCol: {
      flex: 1,
      paddingRight: 16,
    },
    neighborLabel: {
      fontSize: 16,
      fontWeight: '800',
      color: '#FFFFFF',
      marginBottom: 5,
      letterSpacing: -0.2,
    },
    neighborSub: {
      fontSize: 12,
      color: 'rgba(255,255,255,0.50)',
      fontWeight: '400',
      lineHeight: 17,
      marginBottom: 12,
    },
    neighborCtaRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    neighborCta: {
      fontSize: 13,
      fontWeight: '700',
      color: '#6C8EF5',
    },
    neighborArrow: {
      fontSize: 13,
      fontWeight: '700',
      color: '#6C8EF5',
    },
    neighborIconBox: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: 'rgba(108,142,245,0.15)',
      justifyContent: 'center',
      alignItems: 'center',
      flexShrink: 0,
    },

    // ── Section title ─────────────────────────────
    sectionTitle: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.2,
      marginBottom: 14,
      textTransform: 'uppercase',
    },

    // ── Menu grid ─────────────────────────────────
    menuGrid: {
      gap: 8,
    },
    menuRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      columnGap: 12,
      marginBottom: 6,
    },
    menuRowCentered: {
      justifyContent: 'center',
    },
    menuItem: {
      flex: 1,
      alignItems: 'center',
      marginBottom: 16,
      maxWidth: '33.33%',
    },
    menuItemSpacer: {
      flex: 1,
      maxWidth: '33.33%',
    },
    menuIconContainer: {
      width: 72,
      height: 72,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
      shadowColor: isDark ? '#FFFFFF' : 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: isDark ? 0.16 : 0,
      shadowRadius: isDark ? 12 : 0,
      elevation: isDark ? 4 : 0,
    },
    menuLabel: {
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
      lineHeight: 16,
      paddingHorizontal: 6,
      width: '100%',
    },

    // ── Legacy / unused ───────────────────────────
    safeArea:         { flex: 1, backgroundColor: colors.background },
    divider:          { width: 1, height: 24, backgroundColor: colors.border, marginHorizontal: 12 },
    filterBtn:        { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
    filterIcon:       { fontSize: 16 },
    bottomNav:        { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', paddingVertical: 40, paddingHorizontal: 25 },
    navItem:          { padding: 8 },
    navIcon:          { fontSize: 26, opacity: 0.4 },
    navIconActive:    { fontSize: 26, opacity: 1 },
    quickActions:     { flexDirection: 'row', paddingHorizontal: 20, marginBottom: 32, gap: 12 },
    actionCard:       { flex: 1, height: 85, borderRadius: 20, padding: 16, justifyContent: 'center' },
    actionCardGray:   { backgroundColor: '#1C2340' },
    actionCardGreen:  { backgroundColor: '#7C1D1D' },
    actionCardOrange: { backgroundColor: colors.primary },
    actionIcon:       { fontSize: 26, marginBottom: 6 },
    actionText:       { fontSize: 11, color: colors.onPrimary, fontWeight: '700', lineHeight: 14 },
    actionTextWhite:  { fontSize: 11, color: colors.onPrimary, fontWeight: '700', lineHeight: 14 },
  });
